<Content>
    adaptive_height: True

    TwoLineIconListItem:
        id: icon_list
        text: "(050)-123-45-67"
        secondary_text: "Mobile"

        IconLeftWidget:
            icon: 'phone'

<Convocados>:
    id: team
    MDBoxLayout:
        orientation: 'vertical'
        padding: 0, 50, 0, 0
        ScrollView:
            MDGridLayout:
                id: box
                cols: 1
                adaptive_height: True
